### ISSUE TITLE
Jumperless app firmware updater seems to have an error.

### ISSUE THREAD

**Issue by ReanimationXP** [Architeuthis-Flux/Jumperless#35]
There appears to be an issue with the firmware updater in Jumperless.exe.  I get the following output when running it, even as admin.  I suspect the error has something to do with 'ser.close()' on line 386 of JumperlessWokwiBridge.py.

`C:\Jumperless>Jumperless.exe

1: COM6 [USB Serial Device (COM6)]
2: COM7 [USB Serial Device (COM7)]

Autodetected Jumperless at COM6
Autodetected USB-Serial at COM7

 'menu'   to open the Bridge App menu
 'skip'   to disable Wokwi updates and just use as a terminal
 'update' to force firmware update - yours is up to date (1.3.17)
 'slots'  to assign Wokwi projects to slots (this menu)
    ^--   (you can enter these commands at any time)

  ENTER   to accept and go to Jumperless

      'x' to clear all slots
      'c' to clear a single slot

Enter the slot number you'd like to assign a project to:

slot 0
slot 1
slot 2
slot 3
slot 4
slot 5
slot 6
slot 7

slot > update

Would you like to update your Jumperless with the latest firmware? Y/n

Downloading latest firmware...
Traceback (most recent call last):
  File "JumperlessWokwiBridge.py", line 1244, in <module>
  File "JumperlessWokwiBridge.py", line 916, in assignWokwiSlots
  File "JumperlessWokwiBridge.py", line 452, in updateJumperlessFirmware
NameError: name 'ser' is not defined. Did you mean: 'set'?
[48448] Failed to execute script 'JumperlessWokwiBridge' due to unhandled exception!`

**Comment by Architeuthis-Flux** [comment]
Interesting. Would you mind testing something for me? [Load an older version of the firmware](https://github.com/Architeuthis-Flux/Jumperless/releases/tag/1.3.14) (by holding boot, plugging it in, and dropping this file on the drive that pops up), then reopen the app and select Yes when it asks if you'd like to update the firmware.

I'll push a fix anyway, but I'm curious if it's a sequencing thing that happens when you force a firmware update versus letting it auto-update.
